server:
  #SSL configuration
  ssl:
    key-alias: springandjava
    key-store: classpath:springandjava.jks
    key-store-password: spring@123
    key-store-type: PKCS12

spring:
  groovy:
    template:
      cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    show-sql: true

  #Mail configuration
  mail:
    host: localhost
    password: hello
    port: 1025
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          ssl:
            trust: '"*"'
          starttls:
            enable: false
          timeout: 3000
          writetimeout: 5000
    username: hello

  # Thymeleaf Cache disabled
  thymeleaf:
    cache: false

  # Google Oauth Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 84835561841-qm95m0nmfkkculegiee74iaetbkka62d.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile